### ISSUE TITLE
Calismiyor

### ISSUE THREAD

**Issue by elmasgrici** [mcagriaksoy/tcdd-bilet-yer-kontrol#4]
Merhaba, elinize saglik. Ancak program calismiyor. Mesela Konya - İstanbul arası 30.01.2024 tarihinde saat 06:00'da şu an için 258 kişilik boş yer olmasına rağmen, bilet yokmuş gibi tekrar aramaya geçiyor. Acaba TCDD'nin sistem değişikliğinden etkilenmiş olabilir mi? Bir de bütün duraklar yok. Mesela Karaman Bozüyük vb eklenebilir. Tekrar teşekkürler.

**Comment by mcagriaksoy** [comment]
Aynen sitede ufak bir guncelleme olmus, simdi ekliyorum.

**Comment by mcagriaksoy** [comment]
Selam, yeni bir versiyon olusturdum, Musait oldugunda deneyebilirsen cok sevinirim :) Eger sende de calisiyor ise bu issue`yi kapatabiliriz.
